# -------------------部署需要修改---------------------
bots:
  config:
    logs: false
    enable-proxy: false
    tokens:
      BOT_TOKEN: 7507839053:AAFW7PFexmXOLDiG0GQojLEdGQcA2A2lY4g
    background-id: -1003181400582
    # 后台命令管理员ID白名单（必填：填写拥有后台权限的 Telegram user id，空列表表示禁止所有后台命令）
    manager-ids: []
    audit-id: -1003147012451
    publish-id: -1003138818633
    exposure-id: -1002787414688
    address: TMPQSc5YsjLBh9CdYcCH3RmqEAfELFuLMe
    api-key: 9e1edc585fbd72fb1ef129845e3ac911
    web-url: http://45.77.4.60:${server.port}/login
    channel: -1003138818633
# -------------------部署需要修改---------------------

mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true

  global-config:
    # 全局配置
    banner: false
    db-config:
      table-prefix: t_
      # 数据库配置
      id-type: auto
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: QWERT123
    url: jdbc:mysql://127.0.0.1:3306/cdzjbot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true
  redis:
    host: 127.0.0.1
    port: 51379
    password: devrobots
logging:
  level:
    com.db.bots: ERROR